よこさん比較修正

diff --git a/.github/workflows/main_tech0-gen-11-step3-2-node-46.yml b/.github/workflows/main_tech0-gen-11-step3-2-node-46.yml
--- a/.github/workflows/main_tech0-gen-11-step3-2-node-46.yml
+++ b/.github/workflows/main_tech0-gen-11-step3-2-node-46.yml
@@ -16,10 +16,8 @@ jobs:
   build:
     # ubuntu仮想マシンで実行
     runs-on: ubuntu-latest
-
-    # 消さなくて良い？
-    # permissions:
-    #  contents: read #This is required for actions/checkout
+    permissions:
+     contents: read #This is required for actions/checkout
 
     steps:
       # GitHubリポジトリのコードを取得
@@ -51,9 +49,10 @@ jobs:
           cp -r ./.next/static/. ./deploy/.next/static
 
       # 追加コード3
-      # Zipにまとめる
+      # Zipにまとめる命令。
+      # run: zip release.zip ./deploy -r だとディレクトリ位置がずれるため、
+      # current directoryをdeployフォルダへ移動してからzip化。
       - name: Zip artifact for deployment
-      # run: zip release.zip ./deploy -r
         run: |
           cd deploy
           zip -r ../release.zip .
@@ -69,19 +68,25 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     needs: build
-    
+    environment:
+      name: 'Production'
+      # デプロイ後の URL を GitHub に教える おまじない
+      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
+
     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
         with:
           name: node-app
-          path: .
+          # path変更：成果物をリポジトリ直下にばら撒かない（混ざって分かりにくくなるのを防ぐ）
+          path: artifact
 
       # チェック用コード追加 2025.12.21
+      # ★変更：確認対象のディレクトリを artifact に合わせる
       - name: Check files
         run: |
-          ls -la
-          test -f release.zip && echo "OK: release.zip found" || (echo "NG: release.zip not found" && exit 1)
+          ls -la artifact
+          test -f artifact/release.zip && echo "OK: release.zip found" || (echo "NG: release.zip not found" && exit 1)
 
       # 追加コード5 zipを展開
       #- name: Unzip artifact for deployment
@@ -94,5 +99,5 @@ jobs:
           app-name: 'tech0-gen-11-step3-2-node-46'
           slot-name: 'Production'
           # 追加コード4
-          package: release.zip
+          package: artifact/release.zip
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_297900262A6B4E36AAB97E6F32B7B815 }}
